default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: carriers_app_development
test:
  <<: *default
  database: carriers_app_test
production:
  <<: *default
  database: carriers_app_production
  username: carriers_app
  password: <%= ENV['CARRIERS_APP_DATABASE_PASSWORD'] %>
