default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
development:
  <<: *default
  database: carriers_app_development
test:
  <<: *default
  database: carriers_app_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
